// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvirnmqoonkauanvslun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2aXJubXFvb25rYXVhbnZzbHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mzc5NzcsImV4cCI6MjA2NjUxMzk3N30.FGswJLV_jUUkkGbhuxwJXaSBnpzT9m73Rnw9dBBZ_70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);